"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ReFlowDownloadClient.py']
DATA_FILES = [
    ('images', [
        'images/reflow.icns',
        'images/reflow.ico',
        'images/reflow_text.gif'
    ])
]
OPTIONS = {
    'argv_emulation': False,
    'iconfile': 'images/reflow.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
